import os
from dotenv import load_dotenv
import importlib.util, sys

load_dotenv()
spec = importlib.util.spec_from_file_location(
    "redis_cache", "src/08_redis_cache_pipeline.py"
)
mod = importlib.util.module_from_spec(spec)
spec.loader.exec_module(mod)
ask = mod.ask

EVAL_QUESTIONS = [
    {
        "question": "What is a mutable default argument in Python?",
        "ground_truth": "a mutable default argument is a default argument that is a mutable object, such as a list, and is evaluated only once when the function is defined, not each time the function is called"
    },
    {
        "question": "How does list slicing with assignment work in Python?",
        "ground_truth": "When you do list slicing with assignment, the elements at the specified indices in the list are replaced by the new values."
    },
    {
        "question": "What happens when you call my_set.add([4, 5]) in Python?",
        "ground_truth": "When you call my_set.add([4, 5]) in Python, it will raise a TypeError because lists are not hashable and cannot be added to a set."
    },
    {
        "question": "What is function call and return values in Python?",
        "ground_truth": "A function call in Python is when you invoke a function by its name followed by parentheses, optionally with arguments inside. The return value is the result that the function gives back after execution, which can be used in further expressions or stored in variables."
    },
    {
        "question": "What is dictionary iteration in Python?",
        "ground_truth": "Dictionary iteration in Python refers to the process of looping through the keys, values, or key-value pairs of a dictionary using methods like .keys(), .values(), or .items() in a for loop."
    },
    {
        "question": "What is a byte string in Python and how is it defined?",
        "ground_truth": "A byte string is a sequence of raw 8-bit bytes where each element is represented by an integer from 0 to 255 corresponding to an ASCII value. It is defined by prefixing a standard string literal with the letter 'b' (e.g., b'Python')."
    },
    {
        "question": "What does accessing an individual element by index in a byte string return?",
        "ground_truth": "Accessing a single index of a byte string returns the raw integer byte value at that position, which corresponds directly to the character's numeric ASCII value, rather than returning a single-character string."
    },
    {
        "question": "How does the dictionary .get() method handle a key that is missing when a default value is provided?",
        "ground_truth": "When the specified key is not present in the dictionary, the .get() method safely falls back and returns the second argument passed to it as the default value, preventing a KeyError."
    },
    {
        "question": "What is the default return value of the dictionary .get() method if the requested key is missing and no fallback value is explicitly provided?",
        "ground_truth": "If the key does not exist in the dictionary and no secondary default argument is passed to the .get() method, it will return None by default."
    },
    {
        "question": "How does the modulo assignment operator (%=) evaluate and update a variable?",
        "ground_truth": "The modulo assignment operator computes the remainder when the current value of the left variable is divided by the right operand, and then assigns that resulting remainder value back to the left variable."
    },
    {
        "question": "How can a dictionary comprehension be used to swap keys and values of an existing dictionary?",
        "ground_truth": "By iterating over the original dictionary's key-value pairs using .items(), a dictionary comprehension can declare the old value as the new key and the old key as the new value inside a `{value: key for key, value in dict.items()}` expression."
    },
    {
        "question": "What is the function of the .split() method when applied to user input via input()?",
        "ground_truth": "The .split() method takes a single line of string input and breaks it down into a list of separate substrings based on spaces or specified delimiters."
    },
    {
        "question": "Why is the map() function used when taking multiple numeric user inputs in a single line?",
        "ground_truth": "The map() function is used to apply a specific data type conversion function (like int) to every individual string element generated by splitting the user's input line."
    },
    {
        "question": "Why must list() be wrapped around a map() operation when capturing multiple inputs?",
        "ground_truth": "The map() function returns an abstract map iterator object that does not directly display or store the concrete values in a standard sequence; wrapping it in list() evaluates the iterator and saves the elements inside a mutable list structure."
    }
]



def build_dataset():
    dataset = []
    for item in EVAL_QUESTIONS:
        answer, contexts = ask(item["question"], use_cache=False)
        dataset.append({
            "question": item["question"],
            "answer": answer,
            "contexts": contexts,
            "ground_truth": item["ground_truth"]
        })
    return dataset

def score_faithfulness(answer, contexts, groq_client):
    context_text = "\n".join(contexts)
    prompt = f"""Rate how faithful this answer is to the given context on a scale of 0.0 to 1.0.
    1.0 = every fact in the answer comes directly from the context.
    0.0 = the answer contains hallucinations or unsupported claims.

    Context: {context_text}

    Answer: {answer}

    Reply with only a decimal number between 0.0 and 1.0."""
    
    response = groq_client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[{"role": "user", "content": prompt}]
    )
    try:
        return float(response.choices[0].message.content.strip())
    except:
        return 0.0


def score_answer_relevancy(question, answer, embeddings_model):
    q_emb = np.array(embeddings_model.embed_query(question))
    a_emb = np.array(embeddings_model.embed_query(answer))
    return float(np.dot(q_emb, a_emb) / (np.linalg.norm(q_emb) * np.linalg.norm(a_emb)))


if __name__ == "__main__":
    # dataset = build_dataset()
    # for item in dataset:
    #     print(f"Q: {item['question']}")
    #     print(f"A: {item['answer']}")
    #     print(f"Ground Truth: {item['ground_truth']}")
    #     print(f"Contexts: {item['contexts']}")
    #     print("\n" + "="*80 + "\n")
    import numpy as np
    from groq import Groq
    from langchain_google_genai import GoogleGenerativeAIEmbeddings

    groq_client = Groq()
    emb_model = GoogleGenerativeAIEmbeddings(model="models/gemini-embedding-001")

    print("Building dataset...")
    raw = build_dataset()

    faithfulness_scores = []
    relevancy_scores = []

    for i, item in enumerate(raw):
        print(f"\n[{i+1}/{len(raw)}] {item['question'][:60]}...")
        f_score = score_faithfulness(item["answer"], item["contexts"], groq_client)
        r_score = score_answer_relevancy(item["question"], item["answer"], emb_model)
        faithfulness_scores.append(f_score)
        relevancy_scores.append(r_score)
        print(f"  Faithfulness: {f_score:.2f} | Answer Relevancy: {r_score:.2f}")

    avg_f = sum(faithfulness_scores) / len(faithfulness_scores)
    avg_r = sum(relevancy_scores) / len(relevancy_scores)

    print(f"\n{'='*50}")
    print(f"RAGAS Results ({len(raw)} questions)")
    print(f"  Faithfulness:     {avg_f:.4f}  (target > 0.75)")
    print(f"  Answer Relevancy: {avg_r:.4f}  (target > 0.70)")
    print(f"{'='*50}")
